#!/bin/bash
#Simple bash script to perform arithmetic operations

#1 --> Ask user to input two numbers 
#       1.1 --> If the numbers field is empty, script ends

#2 --> Provide user a options to do what type of arithmetic operations such as add, subtract, multiply, remainder, quotient 
 #       2.1 ---> If the option field doesn't match with the option as per mentioned, the script ends


echo "Enter first number"
read first

echo "Enter second number"
read second 

if [ -n "$first" ] && [ -n "$second" ]
then
        echo "What would you like to do from the below options"
        echo "***********************"
        echo "Addition: +, Subtract: -, Multiply: *, Quotient:: / Remainder: %, Quit:>
        read option
        echo "***********************"
        if [ -n "$option" ]
        then
                if [ "$option" == "+" ]
                then
                        echo "Addition of $first and $second is: `expr $first + $seco>
                elif [ "$option" == "-" ]
                then
                        echo "Subtraction of $first and $second is: `expr $first - $s>
                elif [ "$option" == "*" ]
                then
                        echo "Muliplication of $first and $second is: `expr $first \*>
                elif [ "$option" == "/" ]
                then
                        echo "Quotient of $first and $second is: `expr $first \% $sec>
                elif [ "$option" == "%" ]
                then
                        echo "Remainder of $first and $second is: `expr $first \/ $se>
                elif [ "$option" == "Q" ]
                then
                        echo "Bye"
                else
                        echo "Invalid Option"
                fi
        else
                echo "Option field is empty, which is not possible"
                echo "Bye"
        fi
elif [ -z "$first" ] && [ -n "$second" ]
then
        echo "First number cannot be empty, Try again"
elif [ -n "$first" ] && [ -z"$second" ]
then
        echo "Second number cannot be empty, Try again"
else
        echo "Both field cannot be empty"
fi

