#!/bin/bash

echo "ENter the domain"
read domain 

echo "Enter the File location"
read file 

rm -rf /home/kali/bash-scripts/sub-domains
if [ -n "$domain" ] && [ -n "$file" ]
then
        if [ -f "$file" ]
        then
                for ip in $(cat $file)
                do
                        host $ip.$domain | grep "has address" |cut -d " " -f1,4 1>
                done
                echo "Finding out the sub-domains. Wait 15 seconds"
                sleep 15 
                if [ -s "/home/kali/bash-scripts/sub-domains" ]
                then
                        echo "Sub-doamins are listed below"
                        echo "****************************"
                        cat /home/kali/bash-scripts/sub-domains | sort -h | uniq >
                else
                        echo "No sub-domains were found for the given domain"
                fi
        else
                echo "File doesnt exist"
        fi
elif [ -n "$domain" ] && [ -z "$file" ]
then
        echo "FIle location field cannot be empty"
elif [ -z "$domain" ] && [ -n "$file" ]
then
        echo "Domain field cannot be empty"
else
        echo "Both field cannot be empty"
fi
