#!/bin/bash
#Always a user to enter the absolute path and the filename
#based upon the above input, the script check whether the file or directory exists or not. 

echo "Enter the file location:Absolute Path"
read location

echo "Enter the file"
read file

if [ -n "$location" ] && [ -n "$file" ]
then
        if [ -e "$location$file" ]
        then
                if [ -d "$location$file" ]
                then
                        echo "Directory exist: $file"
                else
                        echo "File exists: $file"
                fi
        else
                echo "Invalid File path"
        fi

elif [ -n "$location" ] && [ -z "$file" ]
then
        echo "Filename cannot be empty"
elif [ -z "$location" ] && [ -n "$file" ]
then
        echo "File Path cannot be empty"
else
        echo "Both field cannot be empty"
fi
