#!/bin/bash
#Ask the user to input the location (Absolute path) and filename
#Based upon the above input, it check whether file or directory already exist in the system or not. 

echo "Enter the file location:Absolute Path"
read location

echo "Enter the file"
read file

if [ -n "$location" ] && [ -n "$file" ]
then
        if [ -e "$location$file" ]
        then
                if [ -d "$location$file" ]
                then
                        echo "Directory exist: $file"
                else
                        if [ -s "$location$file" ]
                        then
                                echo "File exist and size is greater than zero bytes"
                        else
                                echo "File exist and size is zero bytes"
                        fi
                fi
        else
                echo "Invalid File path"
        fi

elif [ -n "$location" ] && [ -z "$file" ]
then
        echo "Filename cannot be empty"
elif [ -z "$location" ] && [ -n "$file" ]
then
        echo "File Path cannot be empty"
else
        echo "Both field cannot be empty"
fi
